# -*- coding: utf-8 -*-
"""Copy of BERT_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1myj3q2mNC087AKePD3rlxQ9o0w2frB4I
"""

pip install ktrain

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline
import os
os.environ["CURD_DEVICE_ORDER"]="PCI_BUS_ID";
os.environ["CURD_VISIBLE_DEVICE"]="0";

import ktrain
from ktrain import text

import pandas as pd


data = pd.read_csv('/content/777.txt')
data.head(10)

data.groupby('Category').describe()

df_correct=data[data['Category']=='correct']
df_correct.shape

df_incorrect=data[data['Category']=='incorrect']
df_incorrect.shape



df_balanced=pd.concat([df_correct,df_incorrect])
df_balanced.shape
# df_balanced.to_csv('test.csv', index=False)

df_balanced['correct']=df_balanced['Category'].apply(lambda x :1 if x=='correct' else 0)
df_balanced.head(5)

from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test=train_test_split(df_balanced['Message'], df_balanced['Category'], stratify=df_balanced['Category'])
X_train=np.array(X_train)
X_test=np.array(X_test)
y_train=np.array(y_train)
y_test=np.array(y_test)

list(y_train)

len(X_train) ,len(X_test)

print(X_test)

model_name='distilbert-base-uncased'

trans=text.Transformer(model_name, maxlen=128, class_names=['correct','incorrect'])

train_data= trans.preprocess_train(X_train, y_train)
test_data=trans.preprocess_test(X_test, y_test)



train_data.x

model=trans.get_classifier()

learner= ktrain.get_learner(model, train_data=train_data, val_data=test_data, batch_size=16)

learner.lr_find(show_plot=True, max_epochs=6)

learner.fit_onecycle(7 * 1e-4 ,10)

learner.validate()

learner.view_top_losses(n=3, preproc=trans)

predictor=ktrain.get_predictor(learner.model, preproc=trans)

x= "Considering the criticisms of the trait theory outlined above, several researchers have begun to adopt a different perspective of leader individual differences—the leader attribute pattern approach. In contrast to the traditional approach, the leader attribute pattern approach is based on theorists' arguments that the influence of individual characteristics on outcomes is best understood by considering the person as an integrated totality rather than a summation of individual variables. In other words, the leader attribute pattern approach argues that integrated constellations or combinations of individual differences may explain substantial variance in both leader emergence and leader effectiveness beyond that explained by single attributes, or by additive combinations of multiple attributes."

predictor.predict(x)

#predictor.explain(x)
#predictor.save('')